import { useEffect, useRef, useState } from "react"
import type { ChangeEvent, FormEvent } from "react"
import { ArrowLeft, Camera, ChevronDown, X } from "lucide-react"
import DashboardLayout from "../components/dashboard/DashboardLayout"
import { useLanguage } from "../context/LanguageContext"

type Locale = "en" | "fr" | "es"
interface TeamMember { id:number; firstName:string; lastName:string; designation:string; email:string; phone?:string; gender?:string; image:string }
interface FormState { firstName:string; lastName:string; email:string; phone:string; position:string; gender:string }
interface FormErrors { firstName?:string; lastName?:string; email?:string; phone?:string; position?:string; gender?:string; photo?:string }
const STORAGE_KEY="dashstack-team-members"
const DEFAULT_MEMBERS:TeamMember[]=[
{id:1,firstName:"Jason",lastName:"Price",designation:"Admin",email:"janick_parisian@yahoo.com",image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=85"},
{id:2,firstName:"Jukkoe",lastName:"Sisao",designation:"CEO",email:"sibyl_kozey@gmail.com",image:"https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&h=400&q=85"},
{id:3,firstName:"Harriet",lastName:"King",designation:"CTO",email:"nadia_block@hotmail.com",image:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&h=400&q=85"},
{id:4,firstName:"Lenora",lastName:"Benson",designation:"Lead",email:"feil.wallace@kunde.us",image:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=85"},
{id:5,firstName:"Olivia",lastName:"Reese",designation:"Strategist",email:"kemmer.hattie@cremin.us",image:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&h=400&q=85"},
{id:6,firstName:"Bertha",lastName:"Valdez",designation:"CEO",email:"loraine.koelpin@tromp.io",image:"https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&h=400&q=85"},
{id:7,firstName:"Harriett",lastName:"Payne",designation:"Digital Marketer",email:"nannie_west@estrella.tv",image:"https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&h=400&q=85"},
{id:8,firstName:"George",lastName:"Bryant",designation:"Social Media",email:"delmer.kling@gmail.com",image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=85"},
{id:9,firstName:"Lily",lastName:"French",designation:"Strategist",email:"lucienne.herman@hotmail.com",image:"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=400&h=400&q=85"},
{id:10,firstName:"Howard",lastName:"Adkins",designation:"CEO",email:"wiegand.leonor@herman.us",image:"https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&h=400&q=85"},
{id:11,firstName:"Earl",lastName:"Bowman",designation:"Digital Marketer",email:"waino_altenwerth@nicolette.tv",image:"https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=400&h=400&q=85"},
{id:12,firstName:"Patrick",lastName:"Padilla",designation:"Social Media",email:"octavia.nienow@gleichner.net",image:"https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&h=400&q=85"},
]
const EMPTY_FORM:FormState={firstName:"",lastName:"",email:"",phone:"",position:"",gender:""}
const COPY:Record<Locale,Record<string,string>>={
en:{title:"Team",addMember:"Add New Member",addMemberTitle:"Add Team Member",uploadPhoto:"Upload Photo",editPhoto:"Edit Photo",firstName:"First Name",lastName:"Last Name",email:"Your email",phone:"Phone Number",position:"Position",gender:"Gender",firstNamePlaceholder:"Enter your first name",lastNamePlaceholder:"Enter your last name",emailPlaceholder:"Enter your email",phonePlaceholder:"Enter your phone number",positionPlaceholder:"CEO",selectGender:"Select gender",male:"Male",female:"Female",other:"Other",addNow:"Add Now",back:"Back",remove:"Remove team member",required:"This field is required.",lettersOnly:"Please enter letters only.",invalidEmail:"Please enter a valid email address.",phoneInvalid:"Phone number must contain exactly 10 digits.",positionRequired:"Please enter a position.",genderRequired:"Please select a gender.",photoRequired:"Please upload a photo.",removeConfirm:"Remove this team member?"},
fr:{title:"Équipe",addMember:"Ajouter un membre",addMemberTitle:"Ajouter un membre d'équipe",uploadPhoto:"Télécharger une photo",editPhoto:"Modifier la photo",firstName:"Prénom",lastName:"Nom",email:"Votre e-mail",phone:"Numéro de téléphone",position:"Poste",gender:"Genre",firstNamePlaceholder:"Entrez votre prénom",lastNamePlaceholder:"Entrez votre nom",emailPlaceholder:"Entrez votre e-mail",phonePlaceholder:"Entrez votre numéro de téléphone",positionPlaceholder:"PDG",selectGender:"Sélectionnez le genre",male:"Homme",female:"Femme",other:"Autre",addNow:"Ajouter",back:"Retour",remove:"Supprimer ce membre",required:"Ce champ est obligatoire.",lettersOnly:"Veuillez utiliser uniquement des lettres.",invalidEmail:"Veuillez saisir une adresse e-mail valide.",phoneInvalid:"Le numéro doit contenir exactement 10 chiffres.",positionRequired:"Veuillez saisir un poste.",genderRequired:"Veuillez sélectionner un genre.",photoRequired:"Veuillez télécharger une photo.",removeConfirm:"Supprimer ce membre de l'équipe ?"},
es:{title:"Equipo",addMember:"Añadir nuevo miembro",addMemberTitle:"Añadir miembro del equipo",uploadPhoto:"Subir foto",editPhoto:"Editar foto",firstName:"Nombre",lastName:"Apellido",email:"Tu correo electrónico",phone:"Número de teléfono",position:"Puesto",gender:"Género",firstNamePlaceholder:"Introduce tu nombre",lastNamePlaceholder:"Introduce tu apellido",emailPlaceholder:"Introduce tu correo electrónico",phonePlaceholder:"Introduce tu número de teléfono",positionPlaceholder:"CEO",selectGender:"Selecciona el género",male:"Hombre",female:"Mujer",other:"Otro",addNow:"Añadir ahora",back:"Atrás",remove:"Eliminar miembro del equipo",required:"Este campo es obligatorio.",lettersOnly:"Introduce solo letras.",invalidEmail:"Introduce una dirección de correo válida.",phoneInvalid:"El número debe contener exactamente 10 dígitos.",positionRequired:"Introduce un puesto.",genderRequired:"Selecciona un género.",photoRequired:"Sube una foto.",removeConfirm:"¿Eliminar este miembro del equipo?"},
}
function getLocale(language:string):Locale{const v=String(language).toLowerCase();if(v.startsWith("fr")||v==="french")return"fr";if(v.startsWith("es")||v==="spanish")return"es";return"en"}
function readMembers():TeamMember[]{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return DEFAULT_MEMBERS;const parsed=JSON.parse(raw) as TeamMember[];return Array.isArray(parsed)&&parsed.length?parsed:DEFAULT_MEMBERS}catch{return DEFAULT_MEMBERS}}

export default function Team(){
 const {language}=useLanguage(); 
 const t=COPY[getLocale(language)]
 const [members,setMembers]=useState<TeamMember[]>(readMembers); const [isAddingMember,setIsAddingMember]=useState(false)
 const [form,setForm]=useState<FormState>({...EMPTY_FORM}); const [errors,setErrors]=useState<FormErrors>({}); const [photoPreview,setPhotoPreview]=useState(""); const fileRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(members))},[members])
 const openForm=()=>{setForm({...EMPTY_FORM});setErrors({});setPhotoPreview("");if(fileRef.current)fileRef.current.value="";setIsAddingMember(true)}
 const closeForm=()=>{setIsAddingMember(false);setForm({...EMPTY_FORM});setErrors({});setPhotoPreview("")}
 const change=(field:keyof FormState,value:string)=>{let v=value;if(field==="firstName"||field==="lastName")v=value.replace(/[^A-Za-z\s]/g,"");if(field==="email")v=value.toLowerCase();if(field==="phone")v=value.replace(/[A-Za-z]/g,"");setForm(s=>({...s,[field]:v}));setErrors(e=>({...e,[field]:undefined}))}
 const photo=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith("image/")){setErrors(x=>({...x,photo:t.photoRequired}));return}const r=new FileReader();r.onload=()=>{setPhotoPreview(String(r.result||""));setErrors(x=>({...x,photo:undefined}))};r.readAsDataURL(f)}
 const validate=()=>{const e:FormErrors={};if(!form.firstName.trim())e.firstName=t.required;else if(!/^[A-Za-z\s]+$/.test(form.firstName))e.firstName=t.lettersOnly;if(!form.lastName.trim())e.lastName=t.required;else if(!/^[A-Za-z\s]+$/.test(form.lastName))e.lastName=t.lettersOnly;if(!form.email.trim())e.email=t.required;else if(!/^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/.test(form.email))e.email=t.invalidEmail;const digits=form.phone.replace(/\D/g,"");if(!form.phone.trim())e.phone=t.required;else if(digits.length!==10)e.phone=t.phoneInvalid;if(!form.position.trim())e.position=t.positionRequired;if(!form.gender)e.gender=t.genderRequired;if(!photoPreview)e.photo=t.photoRequired;setErrors(e);return Object.keys(e).length===0}
 const submit=(e:FormEvent)=>{e.preventDefault();if(!validate())return;setMembers(cur=>[{id:Date.now(),firstName:form.firstName.trim(),lastName:form.lastName.trim(),designation:form.position.trim(),email:form.email.trim().toLowerCase(),phone:form.phone,gender:form.gender,image:photoPreview},...cur]);closeForm()}
 const remove=(id:number)=>{if(window.confirm(t.removeConfirm))setMembers(cur=>cur.filter(m=>m.id!==id))}
 const input=(field:keyof FormState)=>`w-full h-[52px] rounded-[8px] bg-[#F5F6FA] dark:bg-[#323D4E] border ${errors[field]?"border-[#F93C65]":"border-[#D5D5D5] dark:border-[#4B5668]"} px-4 font-semibold text-[14px] text-[#202224] dark:text-white placeholder:font-normal placeholder:text-[#A6A6A6] focus:outline-none focus:border-[#4880FF] transition-colors`
 return <DashboardLayout><section className="w-full">
  <div className="mb-6 flex flex-col gap-4 sm:mb-7 sm:flex-row sm:items-center sm:justify-between">
   <div className="flex min-w-0 items-center gap-3">{isAddingMember&&<button type="button" onClick={closeForm} aria-label={t.back} title={t.back} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-[#202224] hover:bg-white hover:text-[#4880FF] dark:text-white dark:hover:bg-[#273142]"><ArrowLeft size={20}/></button>}<h1 className="font-sans text-[24px] font-bold leading-none tracking-[-0.11px] text-[#202224] dark:text-white sm:text-[32px]">{isAddingMember?t.addMemberTitle:t.title}</h1></div>
   {!isAddingMember&&<button type="button" onClick={openForm} className="flex h-[48px] w-full items-center justify-center rounded-[6px] bg-[#4880FF] px-6 text-[14px] font-bold text-white shadow-sm transition-all hover:-translate-y-0.5 hover:bg-[#3B6EE8] hover:shadow-md active:scale-95 sm:w-auto">{t.addMember}</button>}
  </div>
  {!isAddingMember&&<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3 xl:grid-cols-4 2xl:gap-[30px]">
   {members.map(m=><article key={m.id} className="group relative flex min-h-[285px] flex-col items-center overflow-hidden rounded-[14px] border border-[#B9B9B9]/20 bg-white p-6 text-center shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg dark:border-[#313D4F] dark:bg-[#273142]">
    <div aria-hidden className="pointer-events-none absolute inset-0 opacity-50 dark:opacity-20" style={{backgroundImage:"radial-gradient(ellipse at 20% 20%, transparent 0 35%, rgba(72,128,255,.08) 35.5%, transparent 36%),radial-gradient(ellipse at 70% 60%, transparent 0 38%, rgba(72,128,255,.06) 38.5%, transparent 39%)",backgroundSize:"180px 120px,220px 150px"}}/>
    <button type="button" onClick={()=>remove(m.id)} aria-label={t.remove} title={t.remove} className="absolute right-3 top-3 z-10 flex h-7 w-7 items-center justify-center rounded-full bg-red-50 text-red-500 opacity-100 shadow-sm transition-all hover:bg-red-500 hover:text-white sm:opacity-0 sm:group-hover:opacity-100 dark:bg-red-500/10"><X size={15} strokeWidth={2.2}/></button>
    <div className="relative z-[1] flex w-full flex-1 flex-col items-center justify-center"><div className="mb-4 h-[100px] w-[100px] overflow-hidden rounded-full ring-4 ring-white/60 dark:ring-[#273142]/60"><img src={m.image} alt={`${m.firstName} ${m.lastName}`} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/></div><h2 className="mb-1 max-w-full truncate px-2 text-[18px] font-bold text-[#202224] dark:text-white">{m.firstName} {m.lastName}</h2><p className="mb-1 text-[14px] font-semibold text-[#202224] dark:text-[#CBD5E1]">{m.designation}</p><p className="w-full truncate px-1 text-[13px] text-[#202224] dark:text-[#AEB8C7]">{m.email}</p></div>
   </article>)}
  </div>}
  {isAddingMember&&<form onSubmit={submit} noValidate className="w-full rounded-[14px] border border-[#B9B9B9]/20 bg-white px-5 py-10 shadow-sm dark:border-[#313D4F] dark:bg-[#273142] sm:px-12 md:px-[100px] md:py-[60px] lg:px-[180px]">
   <div className="mb-10 text-center"><input ref={fileRef} type="file" accept="image/*" onChange={photo} className="hidden"/><button type="button" onClick={()=>fileRef.current?.click()} className="group mx-auto flex h-[80px] w-[80px] items-center justify-center overflow-hidden rounded-full bg-[#ECECEE] shadow-sm transition-transform hover:scale-105 dark:bg-[#E2E8F0]">{photoPreview?<img src={photoPreview} alt={t.editPhoto} className="h-full w-full object-cover"/>:<Camera size={30} strokeWidth={2.4} className="text-[#202224]"/>}</button><button type="button" onClick={()=>fileRef.current?.click()} className="mt-3 text-[14px] font-bold text-[#4880FF] hover:underline">{photoPreview?t.editPhoto:t.uploadPhoto}</button>{errors.photo&&<p className="mt-2 text-[12px] font-semibold text-[#F93C65]">{errors.photo}</p>}</div>
   <div className="mx-auto mb-12 grid max-w-[780px] grid-cols-1 gap-x-[30px] gap-y-7 md:grid-cols-2">
    {([['firstName',t.firstName,t.firstNamePlaceholder],['lastName',t.lastName,t.lastNamePlaceholder],['email',t.email,t.emailPlaceholder],['phone',t.phone,t.phonePlaceholder],['position',t.position,t.positionPlaceholder]] as [keyof FormState,string,string][]).map(([field,label,placeholder])=><div key={field}><label htmlFor={`team-${field}`} className="mb-[10px] block text-[14px] font-semibold text-[#606060] dark:text-gray-300">{label}</label><input id={`team-${field}`} type={field==='email'?'email':field==='phone'?'tel':'text'} inputMode={field==='phone'?'numeric':field==='email'?'email':undefined} value={form[field]} onChange={e=>change(field,e.target.value)} placeholder={placeholder} className={input(field)}/>{errors[field]&&<p className="mt-1.5 text-[12px] font-semibold text-[#F93C65]">{errors[field]}</p>}</div>)}
    <div><label htmlFor="team-gender" className="mb-[10px] block text-[14px] font-semibold text-[#606060] dark:text-gray-300">{t.gender}</label><div className="relative w-full sm:w-[180px]"><select id="team-gender" value={form.gender} onChange={e=>change('gender',e.target.value)} className={`h-[52px] w-full appearance-none rounded-[8px] border bg-[#F5F6FA] px-4 pr-10 text-[14px] font-semibold text-[#202224] outline-none focus:border-[#4880FF] dark:bg-[#323D4E] dark:text-white ${errors.gender?'border-[#F93C65]':'border-[#D5D5D5] dark:border-[#4B5668]'}`}><option value="" disabled>{t.selectGender}</option><option value="Male">{t.male}</option><option value="Female">{t.female}</option><option value="Other">{t.other}</option></select><ChevronDown size={17} className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-[#777] dark:text-gray-300"/></div>{errors.gender&&<p className="mt-1.5 text-[12px] font-semibold text-[#F93C65]">{errors.gender}</p>}</div>
   </div>
   <button type="submit" className="mx-auto block h-[56px] w-full max-w-[274px] rounded-[12px] bg-[#4880FF] text-[18px] font-bold text-white shadow-sm transition-all hover:-translate-y-0.5 hover:bg-[#3B6EE8] hover:shadow-md active:scale-[.98]">{t.addNow}</button>
  </form>}
 </section></DashboardLayout>
}
